### ISSUE TITLE
Link from smartreceipts.co and Play Store to GitHub project

### ISSUE THREAD

**Issue by darthwalsh** [wbaumann/SmartReceiptsLibrary#137]
I found this app on the play store and wanted to learn more about how it was created, but didn't find any links from the Play store listing or from https://www.smartreceipts.co. Since it was AGPL I chanced a google search and found this repo, but it would be nice if those sites linked here!

**Comment by wbaumann** [comment]
Hi @darthwalsh -

I appreciate the feedback. We already have it linked off our website via the guide section:

- https://www.smartreceipts.co/guide#level2article2

Would that work? The play store is a bit more of a challenge, since I'll have to get some of the entries translated again, but I'll see if there's a good place to drop it in :).

Let me know!

**Comment by darthwalsh** [comment]
Aha, I didn't see that at first but it makes sense now. I was looking in the header or footer from the main site, but that's probably findable.

**Comment by wbaumann** [comment]
Sounds good! I'm going to close this for now. Let me know if you'd like me to re-open it
