### ISSUE TITLE
Support for OCR

### ISSUE THREAD

**Issue by ssaavedra** [wbaumann/SmartReceiptsLibrary#15]
Would it be possible to have OCR support, so that the receipt lines could be mechanically read?

I think that would be a killer feature to have on the phone.

**Comment by wbaumann** [comment]
Absolutely agree and it's definitely a big goal for down the line. I've done a lot of investigation/testing  and have broken the problem down into two parts.

First, there's the OCR aspect. OCR is actually a "solved" process in that there are a number of open source libraries out there that can perform the algorithm. If I recall correctly, there's a library, called "tesseract", that HP wrote back in the day in that does a really good job of turning images into a series of characters.

The second half of the challenge is then converting the receipt text into relevant metadata. I personally find this to be the most challenging part of this problem, especially if you wish to support a wide array of different receipts (Smart Receipts is used internationally, so it has to be able to do this). Even something like determining the total price of a particular receipt can be quite difficult - you can't just pick the largest number, since you may be processing a $15 receipt that has a bottom line, stating "20% recommended tip - $3". In this case, the largest number would be "20" and not "15". In addition to this, I'd also have to build in a number of currency corrections to properly differentiate between USD, CAD, EUR, AUD, etc. 

Long term, I'm hoping to leverage "machine learning" to solve this issue - this effectively means feeding 
an intelligent guessing program about 1,000,000+ "known" (i.e. we have the right price, name, etc. info up front) to the program and tweaking a set of parameters until we hit 99+% accuracy. I'm hoping to scale our backend to a different tier before being able to properly handle this.

**Comment by ssaavedra** [comment]
I mostly agree with you.

There could be an interface on-screen for selecting which text you want to
track instead of guessing so much, as an intermediate point. That way the
whole processing could be done on the phone, which would also be a nice
privacy-sensible feature.

The second half of the challenge is then converting the receipt text into
> relevant metadata. I personally find this to be the most challenging part
> of this problem, especially if you wish to support a wide array of
> different receipts (Smart Receipts is used internationally, so it has to be
> able to do this). Even something like determining the total price of a
> particular receipt can be quite difficult - you can't just pick the largest
> number, since you may be processing a $15 receipt that has a bottom line,
> stating "20% recommended tip - $3". In this case, the largest number would
> be "20" and not "15". In addition to this, I'd also have to build in a
> number of currency corrections to properly differentiate between USD, CAD,
> EUR, AUD, etc.
>
The example you post might be solvable by context, on how aligned the text
is with the rest of the numbers in the receipt, or whether it has a
percentage sign attached. But there should be a minimal implementation
before arguing about that, shouldn't it? :-)

Glad to read the idea is somewhere on the scope.

**Comment by wbaumann** [comment]
My thought was always that - if you have to tap where the price is on the screen, isn't it just easier to type it in by hand (especially when considering the processing time for OCR may be somewhat delayed and not 100% accurate)?

However - I agree that MVP is a good idea before the whole thing. Be happy to fire up another investigation at some point. Thanks!

**Comment by wbaumann** [comment]
Resolving this as now closed with the `4.3.0` release. We support OCR via http://taggun.io/

**Comment by ssaavedra** [comment]
The link is broken. Current URL: https://www.taggun.io/

**Comment by wbaumann** [comment]
Whoops my fault - thank you for sharing the correct link!
