### ISSUE TITLE
PDF export fails to include receipt images in report

### ISSUE THREAD

**Issue by eliaweiss** [wbaumann/SmartReceiptsLibrary#167]
When I chose to create a PDF report, the images are missing from the report

[טאא.pdf](https://github.com/wbaumann/SmartReceiptsLibrary/files/3634880/default.pdf)

**Comment by wbaumann** [comment]
@eliaweiss I'm going to close this one in favor of #166

**Comment by eliaweiss** [comment]
Hi wbaumann,
Please note that #166 and #167 are NOT the same issue.

In the case above I deleted the PDF attachments, and the PDF generate doesn't fail, it just comes out with blank imgs. 
See the attached PDF for example. 
10x

**Comment by wbaumann** [comment]
CC @HeinousGames for this one too. We'll merge these fixes over to the release branch as well.

Thanks!

**Comment by wbaumann** [comment]
@eliaweiss -

This one was introduced in:

https://github.com/wbaumann/SmartReceiptsLibrary/pull/161

And fixed in:

https://github.com/wbaumann/SmartReceiptsLibrary/pull/169

The crux of the bug is that we were calling:

```
pdDocument.close();
```

Instead of only closing the image stream, so we were effectively preventing the images from being included. 

Thank you for bringing this to my attention. It should be resolved now!
