### ISSUE TITLE
Feature Request: anonymous receipts option

### ISSUE THREAD

**Issue by jberkus** [wbaumann/SmartReceiptsLibrary#29]
I use Smart Receipts just to collect photos of receipts and then input them into my work system.  As such, I'm really not interested in filling out all of the metadata in the receipts -- for which name is a required option, and slows me down.

What about having a configuration option for "anonymous receipts", where the Name field would get automatically filled in with the timestamp?

(incidentally, thanks for such a great app.  I just switched to it from Expensify, and it's definitely a big step forwards, even aside that it's OSS)

**Comment by wbaumann** [comment]
Glad you really like the app so far! 

I'm actually planning to remove the requirement for the name field as part of the next update. Instead of the forced entry, it'll allow you to keep it blank, so there's no duplicate data there (eg if you were ever to edit the Date field in the future, there could be a mismatch between the name and date). Would that work for you? Within the resultant list, I'd just make the Date appear as the primary field if the name was blank.

**Comment by wbaumann** [comment]
Removed the requirement for the name field in the develop branch:

https://github.com/wbaumann/SmartReceiptsLibrary/commit/399b2399561764523f50c5925e8dfca68f4c25fa

Will cut a release to master and submit an update in the next ~2 weeks or so. Will close this issue then. Thanks!

**Comment by jberkus** [comment]
Wow, fast!  Thanks!

**Comment by wbaumann** [comment]
Closing as this release has been pushed. The UI may still be weird at times, since the cursor still defaults to the name field. I'll look into building some better intelligence for the default field (ie starting at the price if you don't name them) as part of the next update or two. Thanks again for the feedback!

**Comment by jberkus** [comment]
Great, updating my client so I can try it out.  Thanks so much!
