### ISSUE TITLE
google-services.json is missing

### ISSUE THREAD

**Issue by Maheshpurplenode** [wbaumann/SmartReceiptsLibrary#60]
Error:Execution failed for task ':app:processFreeDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  D:\Tested prjcts\SmartReceiptsLibrary-master\app\src\free\debug\google-services.json
  D:\Tested prjcts\SmartReceiptsLibrary-master\app\src\debug\free\google-services.json
  D:\Tested prjcts\SmartReceiptsLibrary-master\app\src\free\google-services.json
  D:\Tested prjcts\SmartReceiptsLibrary-master\app\src\debug\google-services.json
  D:\Tested prjcts\SmartReceiptsLibrary-master\app\google-services.json

how to solve

**Comment by wbaumann** [comment]
Hi @Maheshpurplenode, we currently have builds working immediately out of the box, since we rely on Firebase for a few things. The README documents this in better details: https://github.com/wbaumann/SmartReceiptsLibrary/blob/master/README.md

But the crux of the issue is that you'll need to follow the firebase documentation (https://firebase.google.com/) to configure the appropriate settings on your end as desired. We use this for analytics and supporting automatic backups to Google Drive. If you would prefer, I can create a separate flavor of the app that removes these items entirely? 

Alternatively - let me know what your aims for the build are, and I can walk you through some options. Thanks!

**Comment by wbaumann** [comment]
I'm going to resolve this one to track in this task:

https://github.com/wbaumann/SmartReceiptsLibrary/issues/66

So we can monitor all F-Droid (and all FOSS) items in one place. Thanks!
