### ISSUE TITLE
New receipts appear to not be stored - possible Wifi Permission issue

### ISSUE THREAD

**Issue by rebootd** [wbaumann/SmartReceiptsLibrary#77]
New receipts are not getting stored. I ran logcat while I tried and captured a Wifi permissions issue. My devices is a Nexus 6p, with Android 8.1.0. (May 5 2018 path level)

From logcat:
    
    WifiService: getConnectionInfo uid=10012
    WifiPermissionsUtil: Denied: no location permission
    WifiPermissionsUtil: Denied: The current config is not for an open network.
    WifiHAL : Done!

When I export to CSV file, I can see the line item even though its not shown in app. Restart or reboot - still doesn't show up. 

I bought the paid version on Google Play hoping this would solve the problem in addition to removing ads. Also, I went into app permissions to specifically allow storage access. Network access doesn't show as requested in the Android app permissions view.

**Comment by wbaumann** [comment]
Hi @rebootd , thanks for reaching out about this and apologies for the issue here. 

Is this related to the automatic backups feature for Google Drive? That's the only part of the app that should require Wi-Fi permissions as everything else should be local

If not, could you try the following for me:

1. Open the settings menu with the the app
2. Scroll down towards the bottom
3. Click the "Email for Support" option

This will include some extra logs that I can use to help debug the issue further. Will help you get this resolved asap. Assuming it's a receipt storage issue, the storage access permission shouldn't be a necessary factor, since Android now allows you to save to a "app designated" location without it. 

Thanks,
Will

**Comment by wbaumann** [comment]
Alternatively let me know if you'd prefer to avoid using email, and I can walk you through how to get the exact logs that would be relevant for this behavior. Thanks!

**Comment by wbaumann** [comment]
Closing this issue for now due. Please re-open if you're still having issues!
